### ISSUE TITLE
ERROR: for dev  No such image: 

### ISSUE THREAD

**Issue by linoyabut** [teracyhq/angular-boilerplate#16]
Digest: sha256:79e76e82c9fd54b792e523ec4d851f131aeca92c4de2cc9862dfbab666f5081d
Status: Downloaded newer image for teracy/angular-boilerplate:dev_develop
Recreating 1fd7ed966ede_angulartest_dev_1

ERROR: for dev  No such image: sha256:f2fa4cb7710cb74b2629f33f6fdabd7e61aa5fd337d2d12b879b870d713f9237
ERROR: Encountered errors while bringing up the project.

**Comment by hoatle** [comment]
could you describe the steps to reproduce? this is weird

**Comment by linoyabut** [comment]
I just cloned the repo and removed the existing images just to make it sure that I am not missing anything and run this command "docker-compose pull && docker-compose up -d"

**Comment by linoyabut** [comment]
It seems you have pushed a new image and since then I got the said error.

**Comment by hoatle** [comment]
maybe you should try again

**Comment by linoyabut** [comment]
It worked now. Thanks @hoatle this is a big help for me as I need the headless browser on Jenkins.

**Comment by hoatle** [comment]
yes, it works on travis-ci so it should work on jenkins-ci

**Comment by linoyabut** [comment]
@hoatle, I have used your docker-compose.yml and Dockerfile-dev on my project (same as your project structure as I am using angular-cli) but I am getting the same issue.

**Comment by linoyabut** [comment]
I am not sure what is the content of this image teracy/angular-boilerplate:dev_develop as I can't see the docker file of that image on the docker hub.

**Comment by hoatle** [comment]
it's built by travis-ci (see .travis.yml) from Dockerfile-dev

**Comment by linoyabut** [comment]
@hoatle does this mean that I cannot use my own project structure and use your docker related files?

**Comment by hoatle** [comment]
you should change teracy/angular-boilerplate to your docker image name and build it, use it

**Comment by hoatle** [comment]
yes, you can, just adjust following my docker related files

**Comment by linoyabut** [comment]
@hoatle do i need the travis.yml as I am using Jenkins? Just bear with me, I am new with docker, what do you mean "you should change teracy/angular-boilerplate to your docker image name and build it, use it" can you expound it?

**Comment by hoatle** [comment]
you don't need .travis.yml, you can see build steps in the file anf adjust for jenkins-ci

teracy/angular-boilerplate image (on docker-compose.yml and docker-compose.prod.yml)


I'm going to add docs on how to extend this seed project.

I'm going to add jenkins-ci support + docs for it, too

**Comment by linoyabut** [comment]
@hoatle that's great! Thanks
