### ISSUE TITLE
Running end-to-end tests is not working

### ISSUE THREAD

**Issue by linoyabut** [teracyhq/angular-boilerplate#9]
Docker compose has no e2e command.

**Comment by hoatle** [comment]
thank you for your report, we're going to get this work soon.

**Comment by hoatle** [comment]
it should work (on latest develop branch):

```
$ docker-compose pull && docker-compose up -d
$ docker-compose exec dev npm run e2e
```

fixed by: https://github.com/hoatle/angular-boilerplate/commit/0a652f507934fc8f8bfc52346372285db9eb5963

**Comment by hoatle** [comment]
you can see the ci system setup with travis-ci:
- https://github.com/teracyhq/angular-boilerplate/blob/develop/.travis.yml
- https://travis-ci.org/teracyhq/angular-boilerplate/builds/197365599

**Comment by linoyabut** [comment]
@hoatle , I would like to know on how I extend or even use your project since your made some changes.

**Comment by hoatle** [comment]
@shannnon yes, there are breaking changes, I'll update the docs soon.

Basically, you can do this:

- clone this repo with your project name, for example: git clone <this_repo> <your_project_name>
- copy docker-compose.tpl.yml to docker-compose.yml and adjust the ${variable} that is specific to your project
- copy docker-compose.prod.tml.yml to docker-compose.prod.yml and adjust the ${variable} that is specific to your project

after that, `$ docker-compose build && docker-compose up` should work.

That's manual steps. I'm adding automation with setup.sh (but not yet complete).

I'm working on dynamic generation for these project-specific files, I'll add docs for all when it's done (soon, within this week I guess). After that, I'll release v0.1.0 that is stable to be used.

Btw, I recommend that you should use https://github.com/teracyhq/dev for the development environment, we're using it for all of our projects.

**Comment by linoyabut** [comment]
Thanks for replying on my question.  Looking forward to see final solution.

Have a good one.

**Comment by hoatle** [comment]
@shannnon I've updated the usage instruction on the README file: https://github.com/teracyhq/angular-boilerplate/blob/develop/README.md, please follow it and let me know if there is any problem. It's ready to be released as v0.1.0 now, I just need some time to check it more before the official releasing.

**Comment by linoyabut** [comment]
@hoatle Thanks for the update i will try your changes first thing in the morning and I will let you know if I have encountered any issues.

**Comment by linoyabut** [comment]
@hoatle One quick question, why do you need Vagrant if you are using Docker?

**Comment by hoatle** [comment]
@shannnon this is the reason why http://blog.teracy.com/2016/12/20/teracy-dev-the-only-truly-universal-productive-development-platform-with-docker-on-macos-linux-and-windows/

For example, if you want to test Docker app on your actual Ubuntu server or CentOS server, Vagrant helps. Using Vagrant, you're close to the real production server.

**Comment by linoyabut** [comment]
@hoatle I got this error "./setup.sh: line 5: envsubst: command not found."

Can I run this project without vagrant?

**Comment by hoatle** [comment]
@shannon yes, you can, setup.sh is auto file generation, please look into the file content to generate files to your project manually
